#!/usr/bin/env node
// Renders the dataset as browsable Markdown, one file per language.
//
//   node scripts/catalog.mjs
//
// Reads  : data/languages.json, data/resources/*.json
// Writes : catalog/README.md      index of languages
//          catalog/<language>.md  one page per language
//
// Why this exists: JSON and CSV are for programs. Someone who lands on the repo
// from a link wants to READ the thing — and the notes are the part worth
// reading, which no table can hold. So each page opens with a scannable table
// (name, type, level, price) and then gives every resource its own short
// section underneath. Generated, never hand-edited: the source of truth stays
// data/resources/*.json.
//
// Plain Node ESM, no dependencies. Node 18+.

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'catalog');

const languages = JSON.parse(readFileSync(join(ROOT, 'data', 'languages.json'), 'utf8'));
const langBySlug = new Map(
  (Array.isArray(languages) ? languages : languages.languages || []).map((l) => [l.slug, l])
);

const PRICE = { free: 'Free', freemium: 'Freemium', paid: 'Paid' };
const LEVEL_SHORT = { beginner: 'A', intermediate: 'B', advanced: 'C' };

// Markdown table cells cannot contain a raw pipe, and a link label with one
// silently breaks the row into two columns.
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
// GitHub's heading slugger keeps Unicode letters — \w does not, so `\w` would
// turn "Español con Juan" into `espaol-con-juan` and break every anchor with an
// accent in it. Match what GitHub actually generates.
const anchor = (name) =>
  name
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .trim()
    .replace(/\s+/g, '-');

function levels(r) {
  const set = (r.levels || []).map((l) => LEVEL_SHORT[l]).filter(Boolean);
  return set.length === 3 ? 'A–C' : set.join('/') || '—';
}

function page(slug, rows) {
  const lang = langBySlug.get(slug);
  const title = lang ? `${lang.flag || ''} ${lang.name}`.trim() : slug;
  const native = lang && lang.nativeName && lang.nativeName !== lang.name ? ` · ${lang.nativeName}` : '';
  const sorted = [...rows].sort(
    (a, b) => (b.popularity || 0) - (a.popularity || 0) || a.name.localeCompare(b.name)
  );

  const out = [];
  out.push(`# ${title}${native}`);
  out.push('');
  out.push(
    `${sorted.length} resource${sorted.length === 1 ? '' : 's'}. ` +
      `Generated from [\`data/resources/${slug}.json\`](../data/resources/${slug}.json) — ` +
      `corrections go there, not here.`
  );
  out.push('');
  out.push('| Resource | Type | Level | Price |');
  out.push('| --- | --- | --- | --- |');
  for (const r of sorted) {
    out.push(
      `| [${cell(r.name)}](#${anchor(r.name)}) | ${cell((r.types || []).join(', '))} ` +
        `| ${levels(r)} | ${PRICE[r.price] || '—'} |`
    );
  }
  out.push('');
  out.push('---');
  out.push('');

  for (const r of sorted) {
    out.push(`### ${r.name}`);
    out.push('');
    if (r.pitch) out.push(`*${r.pitch}*`);
    out.push('');
    const facts = [
      (r.types || []).join(', '),
      r.cefr || null,
      PRICE[r.price] || null,
      (r.skills || []).length ? (r.skills || []).join(', ') : null,
    ].filter(Boolean);
    if (facts.length) out.push(facts.join(' · '));
    out.push('');
    if (r.notes) out.push(r.notes);
    out.push('');
    const links = [`[Website](${r.url})`, ...(r.links || []).map((l) => `[${l.label}](${l.url})`)];
    out.push(links.join(' · '));
    out.push('');
  }
  return out.join('\n');
}

const files = readdirSync(join(ROOT, 'data', 'resources')).filter((f) => f.endsWith('.json'));
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const index = [];
for (const f of files.sort()) {
  const slug = f.replace(/\.json$/, '');
  const raw = JSON.parse(readFileSync(join(ROOT, 'data', 'resources', f), 'utf8'));
  const rows = Array.isArray(raw) ? raw : raw.resources || [];
  if (!rows.length) continue;
  writeFileSync(join(OUT, `${slug}.md`), page(slug, rows) + '\n');
  const lang = langBySlug.get(slug);
  index.push({
    slug,
    name: lang ? `${lang.flag || ''} ${lang.name}`.trim() : slug,
    n: rows.length,
    free: rows.filter((r) => r.price === 'free').length,
  });
}

const idx = [
  '# Browse the catalogue',
  '',
  'The dataset as pages you can read, one per language — the notes and the',
  'caveats, not just the links. Generated by `node scripts/catalog.mjs`; edit',
  '[`data/resources/`](../data/resources) instead.',
  '',
  '| Language | Resources | Free |',
  '| --- | ---: | ---: |',
  ...index
    .sort((a, b) => b.n - a.n || a.name.localeCompare(b.name))
    .map((l) => `| [${l.name}](${l.slug}.md) | ${l.n} | ${l.free} |`),
  '',
];
writeFileSync(join(OUT, 'README.md'), idx.join('\n'));

console.log(`catalog/  ${index.length} language pages, ${index.reduce((a, l) => a + l.n, 0)} resources`);
