#!/usr/bin/env node
// Renders the dataset as browsable Markdown, one file per language.
//
//   node scripts/catalog.mjs
//
// Reads  : data/languages.json, data/resources/*.json
// Writes : catalog/README.md      index of languages
//          catalog/<language>.md  one page per language
//
// Why this exists: JSON and CSV are for programs. Someone who lands on the repo
// from a link wants to READ the thing. Each page is one table holding every
// field the dataset has for that language — facets first so they stay on screen,
// pitch and notes last, since those are the columns you read one of rather than
// scan. Generated, never hand-edited: the source of truth stays
// data/resources/*.json.
//
// Plain Node ESM, no dependencies. Node 18+.

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'catalog');

const languages = JSON.parse(readFileSync(join(ROOT, 'data', 'languages.json'), 'utf8'));
const langBySlug = new Map(
  (Array.isArray(languages) ? languages : languages.languages || []).map((l) => [l.slug, l])
);

const PRICE = { free: 'Free', freemium: 'Freemium', paid: 'Paid' };
const LEVEL_SHORT = { beginner: 'A', intermediate: 'B', advanced: 'C' };

// Markdown table cells cannot contain a raw pipe, and a link label with one
// silently breaks the row into two columns.
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
// GitHub's heading slugger keeps Unicode letters — \w does not, so `\w` would
// turn "Español con Juan" into `espaol-con-juan` and break every anchor with an
// accent in it. Match what GitHub actually generates.
const anchor = (name) =>
  name
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .trim()
    .replace(/\s+/g, '-');

function levels(r) {
  const set = (r.levels || []).map((l) => LEVEL_SHORT[l]).filter(Boolean);
  return set.length === 3 ? 'A–C' : set.join('/') || '—';
}

function page(slug, rows) {
  const lang = langBySlug.get(slug);
  const title = lang ? `${lang.flag || ''} ${lang.name}`.trim() : slug;
  const native = lang && lang.nativeName && lang.nativeName !== lang.name ? ` · ${lang.nativeName}` : '';
  const sorted = [...rows].sort(
    (a, b) => (b.popularity || 0) - (a.popularity || 0) || a.name.localeCompare(b.name)
  );

  const out = [];
  out.push(`# ${title}${native}`);
  out.push('');
  out.push(
    `${sorted.length} resource${sorted.length === 1 ? '' : 's'}, everything the dataset holds ` +
      `for this language. Generated from [\`data/resources/${slug}.json\`](../data/resources/${slug}.json) — ` +
      `corrections go there, not here.`
  );
  out.push('');
  // Facets first, prose last: the columns worth scanning stay on screen, and
  // the ones that force a horizontal scroll are the ones you read one of.
  out.push('| Resource | Type | Level | CEFR | Price | Skills | Method | Links | Pitch | Notes |');
  out.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const r of sorted) {
    const extra = (r.links || []).map((l) => `[${cell(l.label)}](${l.url})`).join(' · ');
    out.push(
      [
        `[**${cell(r.name)}**](${r.url})`,
        cell((r.types || []).join(', ')),
        levels(r),
        cell(r.cefr || '') || '—',
        PRICE[r.price] || '—',
        cell((r.skills || []).join(', ')) || '—',
        cell((r.methods || []).join(', ')) || '—',
        extra || '—',
        cell(r.pitch || '') || '—',
        cell(r.notes || '') || '—',
      ].join(' | ')
    );
    out[out.length - 1] = `| ${out[out.length - 1]} |`;
  }
  out.push('');
  return `${out.join('\n')}`;
}

const files = readdirSync(join(ROOT, 'data', 'resources')).filter((f) => f.endsWith('.json'));
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const index = [];
for (const f of files.sort()) {
  const slug = f.replace(/\.json$/, '');
  const raw = JSON.parse(readFileSync(join(ROOT, 'data', 'resources', f), 'utf8'));
  const rows = Array.isArray(raw) ? raw : raw.resources || [];
  if (!rows.length) continue;
  writeFileSync(join(OUT, `${slug}.md`), page(slug, rows) + '\n');
  const lang = langBySlug.get(slug);
  index.push({
    slug,
    label: lang ? `${lang.flag || ''} ${lang.name}`.trim() : slug,
    // Sort on the bare name: the label starts with a flag emoji, and sorting on
    // that orders the list by Unicode codepoint of a country flag, which is a
    // fact about Unicode rather than about languages.
    sortName: lang ? lang.name : slug,
    n: rows.length,
    free: rows.filter((r) => r.price === 'free').length,
  });
}

const idx = [
  '# Browse the catalogue',
  '',
  'The dataset as pages you can read, one per language — the notes and the',
  'caveats, not just the links. Generated by `node scripts/catalog.mjs`; edit',
  '[`data/resources/`](../data/resources) instead.',
  '',
  '| Language | Resources | Free |',
  '| --- | ---: | ---: |',
  ...index
    // Alphabetical, with the language-agnostic page pinned first: it applies to
    // whatever you are learning, so it is not one entry among the others.
    .sort((a, b) =>
      a.slug === 'universal' ? -1 : b.slug === 'universal' ? 1 : a.sortName.localeCompare(b.sortName)
    )
    .map((l) => `| [${l.label}](${l.slug}.md) | ${l.n} | ${l.free} |`),
  '',
];
writeFileSync(join(OUT, 'README.md'), idx.join('\n'));

console.log(`catalog/  ${index.length} language pages, ${index.reduce((a, l) => a + l.n, 0)} resources`);
